routes/web.php
<?php
use Illuminate\Foundation\Auth\User;
use Intervention\Image\Facades\Image;
use App\Http\Controllers\ImageController;
use App\Http\Controllers\User\AlbumController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['prefix'=>'user', 'namespace'=>'User', 'middleware'=>['auth']], function(){
    Route::get('/', 'DashboardController@dashboard')->name('user.index');
    Route::resource('/news', 'NewsController', ['as'=>'user']);
    Route::post('/news/{news}', 'NewsController@update', ['as'=>'user'])->name('user.news.update');
    Route::resource('/slider', 'SliderController', ['as'=>'user']);
    Route::resource('/partners', 'PartnersSliderController', ['as'=>'user']);
    Route::resource('/pages', 'PagesController', ['as' => 'user'])->except(['create', 'store', 'destroy']);
    // Route::resource('/six_photo', 'SixPhotoController', ['as'=>'user']);

    // new selectPhoto
    Route::group(['prefix' => 'select-photo'], function () {
        Route::post('/upload-photo', 'SelectPhotoController@uploadPhoto')->name('user.select-photo.image.upload');
        Route::post('/destroy-photo', 'SelectPhotoController@destroyPhoto')->name('user.select-photo.image.destroy');    
    });
    Route::resource('/select-photo', 'SelectPhotoController', ['as' => 'user'])->except(['create', 'show', 'edit', 'update', 'destroy']);

    // gallery
    Route::group(['prefix' => 'photo-gallery'], function () {
        Route::post('/{photo_gallery}', 'PhotoGalleryController@update')->name('user.photo-gallery.update');
        Route::post('/image/upload-photo', 'PhotoGalleryController@uploadPhoto')->name('user.photo-gallery.image.upload');
        Route::post('/image/destroy-photo', 'PhotoGalleryController@destroyPhoto')->name('user.photo-gallery.image.destroy');    
    });
    Route::resource('/photo-gallery', 'PhotoGalleryController', ['as' => 'user']);

    Route::group(['prefix' => 'albumchange'], function() {
        Route::get('/', 'AlbumController@index')->name('albumchange.index');
    });

    Route::group(['prefix' => 'news/image'], function() {
        Route::get('/', 'ImageController@index')->name('image.index');
        Route::post('/upload', 'ImageController@upload')->name('image.upload');
        Route::post('/destroy', 'ImageController@destroy')->name('image.destroy');
    });

    Route::resource('/blocks', 'BlockController', ['as' => 'user'])->except(['create', 'store', 'destroy']);
    Route::resource('/emploee', 'EmploeeController', ['as' => 'user']);
});


// Front route
Route::get('/', 'HomeController@index')->name('welcome');

//api for article
Route::get('/loadMore', 'HomeController@loadMore')->name('loadMore');
Route::get('/endList', 'HomeController@endList')->name('endList');
Route::get('/albumsVue', 'HomeController@albumsVue')->name('albumsVue');

// end api

Route::get('/news', 'HomeController@news')->name('news');
Route::get('/news/{slug}', 'HomeController@cur_news')->name('cur_news');
Route::get('/map', 'HomeController@map')->name('map');
Route::get('/volunteer', 'HomeController@volunteer')->name('volunteer');
Route::get('/scholarship', 'HomeController@scholarship')->name('scholarship');
Route::get('/albums', 'HomeController@albums')->name('albums');
Route::get('/album', 'HomeController@album')->name('album');
Route::get('/social', 'HomeController@social')->name('social');
Route::get('/social-photo', 'HomeController@getSocialPhoto')->name('social.photo');
Route::get('/department', 'HomeController@department')->name('department');
Route::get('/search', 'HomeController@search')->name('search');

// End front route

Auth::routes(['register' => false, 'reset' => false]);

// Super Admin
Route::prefix('admin')->group( function () {
    Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('admin.login');
    Route::get('/logout', 'Auth\AdminLoginController@logout')->name('admin.logout');
    Route::post('/login', 'Auth\AdminLoginController@login')->name('admin.login.submit');
    Route::resource('/configs', 'Admin\ConfigController', ['as' => 'admin'])->except([
        'create', 'show', 'store', 'destroy'
    ]);
    Route::get('/', 'Admin\AdminController@index')->name('admin.dashboard');
    Route::group(['prefix' => 'user-management', 'namespace' => 'Admin\UserManagement'], function() {
        Route::resource('/users', 'UserController', ['as' => 'admin.user-management'])->except('show');
        Route::resource('/admins', 'AdminController', ['as' => 'admin.user-management'])->except('show');
    });
});

// custom method for user logout
Route::post('user/logout', 'Auth\LoginController@userLogout')->name('user.logout');

app/Http/Controllers/Admin/UserManagement/UserController.php
<?php

namespace App\Http\Controllers\Admin\UserManagement;

use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class UserController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth:admin');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.user-management.users.index', [
            'users' => User::paginate(10),
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.user-management.users.create', [
            'user' => [],
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = $request->validate([
            'name' => ['required', 'string', 'max:255'],
            'email' => ['required', 'string', 'email', 'max:255', 'unique:users'],
            'password' => ['required', 'string', 'min:8', 'confirmed'],
        ]);

        User::create([
            'name' => $request->name,
            'email' => $request->email,
            'password' => bcrypt($request->password)
        ]);

        return redirect()->route('admin.user-management.users.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        return view('admin.user-management.users.edit', [
            'user' => $user,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        $validator = $request->validate([
            'name' => ['required', 'string', 'max:255'],
            'email' => [
                'required',
                'string', 
                'email', 
                'max:255', 
                \Illuminate\Validation\Rule::unique('users')->ignore($user->id),
            ],
            'password' => ['nullable', 'string', 'min:8', 'confirmed'],
        ]);

        $user->name = $request->name;
        $user->email = $request->email;
        
        $request->password == null ?: $user->password = bcrypt($request->password);
        
        $user->save();

        return redirect()->route('admin.user-management.users.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $user->delete();

        return redirect()->route('admin.user-management.users.index');
    }
}

app/Http/Controllers/User/AlbumController.php
<?php

namespace App\Http\Controllers\User;

use Image;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Photos;
use App\Albums;
use Intervention\Image\Response;
use Storage;

class AlbumController extends Controller
{
    // need delete
    public function index(Request $request)
    {
		$album_id = $request->albums;
		$album_title = Albums::where('id', $album_id)->value('title');
        return view('user.album.create', [
			'album_title' => $album_title
		]);
    }

	public function upload(Request $request)
	{
		//dd('exit');
		$image = $request->file('image');

		$imageName = time();
		$extension = $image->getClientOriginalExtension();
		$imageFullName = $imageName . '.' . $extension;
		//$path = $request->file('image')->store('photo', 'public', 'app', 'storage');
		Image::make($image)->save(storage_path('app/public/photo') . '/' . $imageFullName);
		// Image::make($image)->resize(300, 200)->save(storage_path('app/public/cover') . '/' . $imageFullName);
		Photos::create([
			'albums_id' => 42,
			//'albums_id' => $request->albumid,
			'photo'  => 'photo/' . $imageFullName
		]);
		//return Response(200, 200);
		return redirect()->route('user.albums');
	}

	public function destroy(Request $req)
    {
		$image = $req->img;

        if (Storage::disk('public')->exists($image['src']) )  {
			Storage::disk('public')->delete($image['src']);
		}
		Photos::where('id', $image['id'])->delete();

		return Response(200, 200);
	}
}

app/Http/Controllers/User/BlockController.php
<?php

namespace App\Http\Controllers\User;

use App\Block;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Storage;
use Illuminate\Validation\Rule;

class BlockController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view ('user.blocks.index', [
            'blocks' => Block::infoBlocks()->paginate(6),
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('user.blocks.create', [
            'block' => []
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $dataValidate = $request->validate([
            'type' => 'required|integer',
            'title' => 'required|string|max:255',
            'link' => 'required_if:type,0',
            'img' => 'required_if:type,0|image|max:2048', // image
            'text' => 'required|string',
            'link' => 'required_if:type,0|max:255',
        ]);
        

        if ($request->hasFile('img') ) {
            $path = $request->file('img')->store('uploads', 'public');
        } else {
            $path = null;
        }

        $block = Block::create([
            'title' => $request->title,
            'img' => $path,
            'text' => $request->text,
            'link' => $request->link,
            'type' => $request->type,
        ]);

        return redirect()->route('user.blocks.show', $block);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Block  $block
     * @return \Illuminate\Http\Response
     */
    public function show(Block $block)
    {
        return view('user.blocks.show', [
            'block' => $block,
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Block  $block
     * @return \Illuminate\Http\Response
     */
    public function edit(Block $block)
    {
        return view('user.blocks.edit', [
            'block' => $block,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Block  $block
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Block $block)
    {
        if ($block->type == 1) {
            $dataValidate = $request->validate([
                'title' => 'required|string|max:255',
                'text' => 'required|string',
                'type' => 'required|boolean'
            ]);
        } else {
            $dataValidate = $request->validate([
                'title' => 'required|string|max:255',
                'img' => 'nullable|image|max:2048',
                'text' => 'required|string',
                'link' => 'required|url|max:255',
                'type' => 'required|boolean'
            ]);
        }
        
        if ($request->hasFile('img') ) {
            $file = $request->img->store('uploads', 'public');
            if (Storage::disk('public')->exists($block->img) )  {
                Storage::disk('public')->delete($block->img);
            }
        } else {
            $file = $block->img;  
        }

        if ($block->type == 1) {
            $block->update([
                'title' => $request->title,
                'text' => $request->text,
                'type' => $request->type
            ]);
        } else {
            $block->update([
                'title' => $request->title,
                'img' => $file,
                'text' => $request->text,
                'link' => $request->link,
                'type' => $request->type
            ]);
        }
        
        
        return redirect()->route('user.blocks.show', $block);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Block  $block
     * @return \Illuminate\Http\Response
     */
    public function destroy(Block $block)
    {
        if (Storage::disk('public')->exists($block->img) ) {
            Storage::disk('public')->delete($block->img);
        }
        $block->delete();

        return redirect()->route('user.blocks.index');
    }
}

app/Http/Controllers/User/CategoryController.php
<?php

namespace App\Http\Controllers\User;

use App\Category;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('user.categories.index', [
           'categories' => Category::paginate(10)
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('user.categories.create', [
            'category'   => [],
            'categories' => Category::with('children')->where('parent_id', 0)->get(),
            'delimiter'  => ''
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Category::create($request->all());

        return redirect()->route('user.category.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        return view('user.categories.edit', [
            'category'   => $category,
            'categories' => Category::with('children')->where('parent_id', 0)->get(),
            'delimiter'  => ''
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        $category->update($request->except('slug'));
        
        return redirect()->route('user.category.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        $category->delete();

        return redirect()->route('user.category.index');
    }
}

app/Http/Controllers/User/DashboardController.php
<?php

namespace App\Http\Controllers\User;

use App\News;
use App\Category;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App;

class DashboardController extends Controller
{
    //Dashboard

    public function dashboard() {
        // App::setlocale('uk');
        return view('user.dashboard', [
            'new'              => News::lastNew(3),
            'count_new'        => News::count()
        ]);
    }
}

resources/views/user/emploee/_form.blade.php
@push('style')
<link rel="stylesheet" href="{{ asset('css/croppie.css') }}"/>
@endpush

<input type="hidden" name="type" value="2" class="form-control @error('type') is-invalid @enderror">
@error('type')
    <div class="alert alert-danger">{{ $message }}</sdiv>
@enderror

<div class="form-group">
    <label for="title">@lang('messages.pib')</label>
    <input type="text" class="form-control @error('title') is-invalid @enderror" name="title" id="title"
        placeholder="@lang('messages.fpib')" value="@if(old('title') ) {{ old('title') }}@else{{ $emploee->title ?? "" }}@endif"
        required
        maxlength="50"
        onkeyup="inputValidation(this.value, 'title_val', '50')"
    >
    <small id="title_val"></small>
</div>

@error('title')
    <div class="alert alert-danger">{{ $message }}</div>
@enderror

<div class="input-group">
    <input type="file" id="upload" accept="image/*">
</div>

@error('img')
    <div class="alert alert-danger">{{ $message }}</div>
@enderror
<br>
<div class="row">
    
    @isset($emploee->img)
    <div class="col-12 col-md-12 col-lg-6 col-xl-4">
        <img class="photo-edit-square d-block mx-auto" src="{{ $emploee->getPath() }}" />
            <p class="text-center">Існуюче зображення</p>
    </div>
    @endisset
    
    <div class="col-sm-12 col-md-12 col-lg-6 col-xl-4">
        
        <div id="upload-demo"></div>
        <br>
    </div>
    <div class="col-sm-12 col-md-12 col-lg-12 col-xl-4">
        <img class="rounded d-block mx-auto photo-edit-square"  id="img-result" />
        <p class="text-center">Нове зображення</p>
    </div>
</div>
<button class="btn btn-outline-primary upload-result mx-auto d-block btn-send">
    <i class="fas fa-cut"></i> Вирізати
</button>

<input type="hidden" name="img" id="img-base-64">

<div class="form-group">
    <label for="description">Зміст</label>
    <textarea class="form-control @error('text') is-invalid @enderror" name="text" id="description" maxlength="150" onkeyup="inputValidation(this.value, 'text_val', '150')"
        >@if( old('text')) {{ old('text')}} @else{{ $emploee->text ?? "" }}@endif</textarea>
        <small id="text_val"></small>
</div>

@error('text')
    <div class="alert alert-danger">{{ $message }}</div>
@enderror

<button type="submit" class="btn btn-outline-primary">Зберегти</button>

@push('down')
    <script>
        const inputValidation = (str, id, howMutch) => {
            const lng = str.length;
            id = document.getElementById(id);
            id.innerHTML = `${lng} символів з ${howMutch}`;
            if (lng == howMutch) {
                id.classList.add('new_alert', 'new_danger');
            }else {
                id.classList.remove('new_alert', 'new_danger');
            }
        };
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="{{ asset('js/croppie.min.js')}}" defer> </script>
    <script>
        $(function() {
        
        function demoUpload() {
            var $uploadCrop;

            function readFile(input) {
            if (input.files && input.files[0]) {
                console.log('Read file');
                var reader = new FileReader();

                reader.onload = function(e) {
                $(".upload-demo").addClass("ready");
                $uploadCrop
                    .croppie("bind", {
                    url: e.target.result
                    })
                    .then(function() {
                    console.log("jQuery bind complete");
                    });
                };

                reader.readAsDataURL(input.files[0]);
            } else {
                swal("Sorry - you're browser doesn't support the FileReader API");
            }
        }

        $uploadCrop = $("#upload-demo").croppie({
        url: '/img/img_avatar.png',
        enableExif: true,
        boundary: { width: 300, height: 300 },
        viewport: {
            width: 300,
            height: 300,
            type: "circle"
        }
        });

        $("#upload").on("change", function() {
            readFile(this);
        });
        $(".upload-result").on("click", function(ev) {
            ev.preventDefault();
        $uploadCrop
            .croppie("result", {
            type: "canvas",
            format: 'jpeg',
            size: "viewport"
            })
            .then(function(resp) {
            popupResult({
                src: resp
            });
            });
        });
    }
    demoUpload();    
    });

    function popupResult(result) {
        $('#img-result').attr('src', result.src);
        $('#img-base-64').attr('value', result.src);
    }

    
    </script>
@endpush

resources/views/user/emploee/create.blade.php
@extends('user.layouts.app_user')

@section('content')

<div class="container-fluid">
   
        @component('user.components.breadcrumb')
            @slot('title') @lang('messages.emploee') @endslot
            @slot('parent') Головна @endslot
            @slot('active') @lang('messages.workers') @endslot
        @endcomponent
        <div class="row">
            <div class="col">
                <form class="form-horizontal" action="{{route('user.emploee.store')}}" method="post" enctype="multipart/form-data">
                    @csrf
                <!-- {{-- Form include --}} -->
                @include('user.emploee._form')
        
                </form>
            </div>
            
        </div>
</div>
@endsection

resources/views/user/emploee/edit.blade.php
@extends('user.layouts.app_user')

@section('content')

<div class="container-fluid">

    @component('user.components.breadcrumb')
        @slot('title') Редагування @endslot
        @slot('parent') Головна @endslot
        @slot('active') Співробіткник @endslot
    @endcomponent

    <form action="{{route('user.emploee.update', $emploee)}}" method="post" enctype="multipart/form-data">
        @method('PUT')
        @csrf
       {{-- Form include --}}
      @include('user.emploee._form')
      
    </form>
</div>
@endsection

resources/views/user/emploee/index.blade.php
@extends('user.layouts.app_user')

@section('content')

<div class="container-fluid">

@component('user.components.breadcrumb')
    @slot('title') @lang('messages.workers') @endslot
    @slot('parent') Головна @endslot
    @slot('active') @lang('messages.workers') @endslot
@endcomponent

    <a href="{{ route('user.emploee.create') }}" class="btn btn-primary float-left beetwen">
        <i class="fas fa-feather-alt"></i> Додати Співробітника
    </a>

    <table class="table table-striped">
        <thead>
            <th>@lang('messages.workers')</th>
            <th class="text-right action">Дія</th>
        </thead>
        <tbody>
            @forelse ($emploee as $worker)
                <tr>
                    <td>{{ $worker->title }}</td>
                    <td class="float-right">
                    <form onsubmit="if(confirm('Видвлити?') ){ return true } else { return false }"
                        action="{{ route('user.emploee.destroy', $worker) }}" method="post">
                        @csrf
                        @method('DELETE')
                        
                        <a class="btn btn-default" href="{{route('user.emploee.edit', $worker) }}"
                            title="Редагувати"><i class="fas fa-edit"></i>
                        </a>
                        <a class="btn btn-default" href="{{route('user.emploee.show', $worker) }}"
                            title="Переглянути">
                            <i class="far fa-eye"></i>
                        </a>

                        <button type="submit" title="Видалити" class="btn"><i class="fas fa-trash-alt"></i></button>
                        </form>
                    </td>
                </tr>
            @empty
                <tr>
                    <td colspan="2" class="text-center"><h2>Дані відсутні</h2></td>
                </tr>
            @endforelse
        </tbody>
        <tfoot>
            <tr>
                <td colspan="2">
                    <ul class="pagination float-right">
                        {{$emploee->links()}}
                    </ul>
                </td>
            </tr>
        </tfoot>
    </table>
</div>

@endsection

resources/views/user/emploee/show.blade.php
<!-- add from layouts -->
@extends('user.layouts.app_user')

@section('content')

<div class="container-fluid">

    @component('user.components.breadcrumb')
        @slot('title') @lang('messages.emploee') @endslot
        @slot('parent') Головна @endslot
        @slot('active') {{ $emploee->title }} @endslot
    @endcomponent

    <br>

    <a role="button" href="{{ route('user.emploee.index') }}" class="btn btn-outline-info">@lang('messages.back')</a>
    <a role="button" href="{{ route('user.emploee.edit', $emploee) }}" class="btn btn-success">@lang('messages.edit')</a>
    <br><br>
    <table class="table table-striped">
        <thead>
            <th>Поле</th>
            <th>Значення</th>
        </thead>
        <tbody>
            <tr>
                <td>@lang('messages.fpib')</td>
                <td>{{ $emploee->title }}</td>
            </tr>
            @isset($emploee->img)
            <tr>
                <td>@lang('messages.photo')</td>
                <td><img src="{{ $emploee->getPath() }}" alt="альтернативный текст" width="250"></td>
            </tr>
            @endisset
            
            <tr>
                <td>@lang('messages.content')</td>
                <td>{!! $emploee->text !!}</td>
            </tr>
        </tbody>
    </table>

</div>

@endsection