routes/web.php
<?php
use Illuminate\Foundation\Auth\User;
use Intervention\Image\Facades\Image;
use App\Http\Controllers\ImageController;
use App\Http\Controllers\User\AlbumController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['prefix'=>'user', 'namespace'=>'User', 'middleware'=>['auth']], function(){
    Route::get('/', 'DashboardController@dashboard')->name('user.index');
    Route::resource('/news', 'NewsController', ['as'=>'user']);
    Route::post('/news/{news}', 'NewsController@update', ['as'=>'user'])->name('user.news.update');
    Route::resource('/slider', 'SliderController', ['as'=>'user']);
    Route::resource('/partners', 'PartnersSliderController', ['as'=>'user']);
    Route::resource('/pages', 'PagesController', ['as' => 'user'])->except(['create', 'store', 'destroy']);
    // Route::resource('/six_photo', 'SixPhotoController', ['as'=>'user']);

    // new selectPhoto
    Route::group(['prefix' => 'select-photo'], function () {
        Route::post('/upload-photo', 'SelectPhotoController@uploadPhoto')->name('user.select-photo.image.upload');
        Route::post('/destroy-photo', 'SelectPhotoController@destroyPhoto')->name('user.select-photo.image.destroy');    
    });
    Route::resource('/select-photo', 'SelectPhotoController', ['as' => 'user'])->except(['create', 'show', 'edit', 'update', 'destroy']);

    // gallery
    Route::group(['prefix' => 'photo-gallery'], function () {
        Route::post('/{photo_gallery}', 'PhotoGalleryController@update')->name('user.photo-gallery.update');
        Route::post('/image/upload-photo', 'PhotoGalleryController@uploadPhoto')->name('user.photo-gallery.image.upload');
        Route::post('/image/destroy-photo', 'PhotoGalleryController@destroyPhoto')->name('user.photo-gallery.image.destroy');    
    });
    Route::resource('/photo-gallery', 'PhotoGalleryController', ['as' => 'user']);

    Route::group(['prefix' => 'albumchange'], function() {
        Route::get('/', 'AlbumController@index')->name('albumchange.index');
    });

    Route::group(['prefix' => 'news/image'], function() {
        Route::get('/', 'ImageController@index')->name('image.index');
        Route::post('/upload', 'ImageController@upload')->name('image.upload');
        Route::post('/destroy', 'ImageController@destroy')->name('image.destroy');
    });

    Route::resource('/blocks', 'BlockController', ['as' => 'user'])->except(['create', 'store', 'destroy']);
    Route::resource('/emploee', 'EmploeeController', ['as' => 'user']);
});


// Front route
Route::get('/', 'HomeController@index')->name('welcome');

//api for article
Route::get('/loadMore', 'HomeController@loadMore')->name('loadMore');
Route::get('/endList', 'HomeController@endList')->name('endList');
Route::get('/albumsVue', 'HomeController@albumsVue')->name('albumsVue');

// end api

Route::get('/news', 'HomeController@news')->name('news');
Route::get('/news/{slug}', 'HomeController@cur_news')->name('cur_news');
Route::get('/map', 'HomeController@map')->name('map');
Route::get('/volunteer', 'HomeController@volunteer')->name('volunteer');
Route::get('/scholarship', 'HomeController@scholarship')->name('scholarship');
Route::get('/albums', 'HomeController@albums')->name('albums');
Route::get('/album', 'HomeController@album')->name('album');
Route::get('/social', 'HomeController@social')->name('social');
Route::get('/social-photo', 'HomeController@getSocialPhoto')->name('social.photo');
Route::get('/department', 'HomeController@department')->name('department');
Route::get('/search', 'HomeController@search')->name('search');

// End front route

Auth::routes(['register' => false, 'reset' => false]);

// Super Admin
Route::prefix('admin')->group( function () {
    Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('admin.login');
    Route::get('/logout', 'Auth\AdminLoginController@logout')->name('admin.logout');
    Route::post('/login', 'Auth\AdminLoginController@login')->name('admin.login.submit');
    Route::resource('/configs', 'Admin\ConfigController', ['as' => 'admin'])->except([
        'create', 'show', 'store', 'destroy'
    ]);
    Route::get('/', 'Admin\AdminController@index')->name('admin.dashboard');
    Route::group(['prefix' => 'user-management', 'namespace' => 'Admin\UserManagement'], function() {
        Route::resource('/users', 'UserController', ['as' => 'admin.user-management'])->except('show');
        Route::resource('/admins', 'AdminController', ['as' => 'admin.user-management'])->except('show');
    });
});

// custom method for user logout
Route::post('user/logout', 'Auth\LoginController@userLogout')->name('user.logout');

app/Http/Controllers/Admin/UserManagement/AdminController.php
<?php

namespace App\Http\Controllers\Admin\UserManagement;

use App\Admin;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class AdminController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth:admin');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.user-management.admins.index', [
            'admins' => Admin::paginate(10),
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.user-management.admins.create', [
            'admin' => [],
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = $request->validate([
            'name' => ['required', 'string', 'max:255'],
            'email' => ['required', 'email', 'max:255', 'unique:admins'],
            'password' => ['required', 'string', 'min:8', 'confirmed'],
        ]);

        Admin::create([
            'name' => $request->name,
            'email' => $request->email,
            'password' => bcrypt($request->password)
        ]);

        return redirect()->route('admin.user-management.admins.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Admin  $admin
     * @return \Illuminate\Http\Response
     */
    public function show(Admin $admin)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Admin  $admin
     * @return \Illuminate\Http\Response
     */
    public function edit(Admin $admin)
    {
        return view('admin.user-management.admins.edit', [
            'admin' => $admin
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Admin  $admin
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Admin $admin)
    {
        $validator = $request->validate([
            'name' => ['required', 'string', 'max:255'],
            'email' => [
                'required',
                'string',
                'email',
                'max:255',
                \Illuminate\Validation\Rule::unique('admins')->ignore($admin->id),
            ],
            'password' => ['nullable', 'string', 'min:8', 'confirmed'],
        ]);
        
        $admin->name = $request->name;
        $admin->email = $request->email;

        $request->password == null ?: $admin->password = bcrypt($request->password);

        $admin->save();

        return redirect()->route('admin.user-management.admins.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Admin  $admin
     * @return \Illuminate\Http\Response
     */
    public function destroy(Admin $admin)
    {
        if (Auth::id() !== $admin->id) {
            $admin->delete();
            return redirect()->route('admin.user-management.admins.index');

        } else {
            return redirect()->route('admin.user-management.admins.index');
        }
       
    }
}

app/Http/Controllers/Admin/UserManagement/UserController.php
<?php

namespace App\Http\Controllers\Admin\UserManagement;

use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class UserController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth:admin');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.user-management.users.index', [
            'users' => User::paginate(10),
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.user-management.users.create', [
            'user' => [],
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = $request->validate([
            'name' => ['required', 'string', 'max:255'],
            'email' => ['required', 'string', 'email', 'max:255', 'unique:users'],
            'password' => ['required', 'string', 'min:8', 'confirmed'],
        ]);

        User::create([
            'name' => $request->name,
            'email' => $request->email,
            'password' => bcrypt($request->password)
        ]);

        return redirect()->route('admin.user-management.users.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        return view('admin.user-management.users.edit', [
            'user' => $user,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        $validator = $request->validate([
            'name' => ['required', 'string', 'max:255'],
            'email' => [
                'required',
                'string', 
                'email', 
                'max:255', 
                \Illuminate\Validation\Rule::unique('users')->ignore($user->id),
            ],
            'password' => ['nullable', 'string', 'min:8', 'confirmed'],
        ]);

        $user->name = $request->name;
        $user->email = $request->email;
        
        $request->password == null ?: $user->password = bcrypt($request->password);
        
        $user->save();

        return redirect()->route('admin.user-management.users.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $user->delete();

        return redirect()->route('admin.user-management.users.index');
    }
}

resources/views/admin/user-management/admins/_form.blade.php
@if($errors->any() )
    <ul class="alert alert-danger">
        @foreach($errors->all() as $error)
            <li>{{ $error }}</li>
        @endforeach
    </ul>
@endif
<div class="form-group">
    <label for="name">Ім'я</label>
    <input type="text" class="form-control" name="name" id="name"
           placeholder="Введіть ім'я" value="@if( old('name') ) {{old('name')}}@else{{$admin->name ?? '' }}@endif" maxlength="255" onkeyup="inputValidation(this.value, 'name_val', '255')">
    <small id="name_val"></small>
</div>

<div class="form-group">
    <label for="title">Email</label>
    <input type="text" class="form-control" name="email" id="email"
           placeholder="Введіть email" value="@if( old('email') ) {{ old('email')}}@else{{$admin->email ?? '' }}@endif" maxlength="255" onkeyup="inputValidation(this.value, 'email_val', '255')">
    <small id="email_val"></small>
</div>

<div class="form-group">
    <label for="title">Пароль</label>
    <input type="password" class="form-control" name="password" id="password"
           placeholder="Введіть пароль"
    >
</div>

<div class="form-group">
    <label for="title">Підтвердження пароля</label>
    <input type="password" class="form-control" name="password_confirmation" id="title"
           placeholder="Введіть пароль повторно"
    >
</div>

<button class="btn btn-primary" type="submit">Зберегти</button>


@push('down_adm')
    <script>
        const inputValidation = (str, id, howMutch) => {
            const lng = str.length;
            id = document.getElementById(id);
            id.innerHTML = `${lng} символів з ${howMutch}`;
            if (lng == howMutch) {
                id.classList.add('new_alert', 'new_danger');
            }else {
                id.classList.remove('new_alert', 'new_danger');
            }
        };
    </script>
@endpush

resources/views/admin/user-management/admins/create.blade.php
@extends('admin.layouts.app_admin')
@section('meta_title', 'Додавання адміністратора')
@section('content')
<div class="container-fluid">
    @component('admin.components.breadcrumbs')
        @slot('title') Створення корустувача @endslot
        @slot('parent') Головна @endslot
        @slot('active') Користувач @endslot
    @endcomponent

    <form action="{{ route('admin.user-management.admins.store') }}" method="post">
        @csrf

        {{-- include form--}}
        @include('admin.user-management.admins._form')

    </form>

</div>
@endsection

resources/views/admin/user-management/admins/edit.blade.php
@extends('admin.layouts.app_admin')
@section('meta_title', 'Редагування даних адміністратора')
@section('content')
<div class="container-fluid">
    @component('admin.components.breadcrumbs')
        @slot('title') Редагування @endslot
        @slot('parent') Головна @endslot
        @slot('active') Адмністратор @endslot
    @endcomponent

    <form action="{{ route('admin.user-management.admins.update', $admin) }}" method="post">
        @method('PUT')
        @csrf
        
        {{-- include form--}}
        @include('admin.user-management.admins._form')

    </form>

</div>
@endsection

resources/views/admin/user-management/admins/index.blade.php
@extends('admin.layouts.app_admin')
@section('meta_title', 'Керування адмністратораторами')
@section('content')
<div class="container-fluid">
    @component('admin.components.breadcrumbs')
        @slot('title') Адмністратори @endslot
        @slot('parent') Головна @endslot
        @slot('active') Всі Адмністратори @endslot
    @endcomponent

    <a href="{{ route('admin.user-management.admins.create') }}" class="btn btn-primary">
        <i class="far fa-plus-square"></i> Додати адміністратора
    </a>

    <br>
    </br>

    <table class="table table-striped">
        <thead>
            <th>Ім'я</th>
            <th>Email</th>
            <th class="text-right">Дії</th>
        </thead>
        <tbody>
        @forelse($admins as $admin)
            <tr>
                <td>{{ $admin->name }}</td>
                <td>{{ $admin->email }}</td>
                <td class="text-right">
                    <form action="{{ route('admin.user-management.admins.destroy', $admin) }}"
                        onsubmit="if(confirm('Справді видалити?') ) { return true} else { return false }" 
                        method="post">
                        @csrf
                        @method('DELETE')
                        
                        <a class="btn btn-default" href="{{ route('admin.user-management.admins.edit', ['id'=> $admin->id]) }}">
                            <i class="far fa-edit"></i>
                        </a>
                        @if ( Auth::id() !== $admin->id)
                            <button type="submit" class="btn"><i class="fas fa-trash-alt"></i></button>
                        @endif
                        
                    </form>
                </td>
            </tr>
            @empty
            <tr>
                <td colspan="3">
                    <h2 class="text-center">Записи відсутні!</h2>
                </td>
            </tr>

        @endforelse
        </tbody>
        <tfoot>
            <tr>
                <td colspan="3">
                    <ul class="pagination">
                        {{ $admins->links() }}
                    </ul>
                </td>
            </tr>
        </tfoot>     

    </table>
</div>
@endsection